### PR TITLE
Fix Windows in GitHub actions

### PR DESCRIPTION
**Pull request by MartinSalinas98**

### CODE REVIEW

**Comment by MartinSalinas98** [comment]
The issue is with the [external cmake action](https://github.com/threeal/cmake-action), not with Windows itself. It just happens to occur with Windows because the CUDA_PATH has spaces for this OS, and that action can't take `option` parameters with spaces.

Working on a fix for the external action.

**Comment by oierlauzi** [comment]
For this repo, should we go without the CMake action and manually set the command?

**Comment by MartinSalinas98** [comment]
For now, the fix in the cmake action is in master branch only, and will be coming to release 2.1.0 (as the developer said), which should happen fairly soon.

But the main issue here is that cmake is not being able to detect CUDA.
I'd suggest fixing that issue before deciding what to do (likely running the command manually until version 2.1.0 is out, or changing the cmake action to master until that release is out and then fixing the version again)

**Comment by oierlauzi** [comment]
Changing to master will not work, as https://github.com/gigabit-clowns/xmipp4-communication-mpi/pull/14 (possibly a CMake action related bug, not feature) is also applicable here. I would try to fix it in a "manual" version and then use the action once it is released.

**Comment by oierlauzi** [comment]
Maybe, we should notify the author about this issue? The former test is a minimal example where the only difference from working to not working is the CMake action version

**Comment by MartinSalinas98** [comment]
> Maybe, we should notify the author about this issue? The former test is a minimal example where the only difference from working to not working is the CMake action version. If the changes make it into v2.1, this will be messy for us

Sure, seems like a good idea, I'll get in touch with him about it

**Comment by MartinSalinas98** [comment]
In the meantime, we might want to use the manual cmake command

**Comment by MartinSalinas98** [comment]
Already solved by #16.

**Pull request closed without merging**
