### PR TITLE
Created action

### PR DESCRIPTION
**Pull request by oierlauzi**

### CODE REVIEW

**Comment by MartinSalinas98** [comment]
The issue found is that, for Windows actions, it is running out of disk space up on CUDA installation.

This happens because Windows runners use two drives: C and D. D has ~10 GB, and happens to be the default drive for cloning & package installations. Meanwhile, C has ~80 GB free.

Therefore, we just need to figure out how to install CUDA in drive C.

**Comment by oierlauzi** [comment]
What if we reduce the installation size as much as possible using subpackages. In the conceivable future these would be the requirements:
sub-packages:
- nvcc
non-cuda-sub-packages:
- libcublas
- libcufft
- libcusolver

**Comment by MartinSalinas98** [comment]
> What if we reduce the installation size as much as possible using subpackages. In the conceivable future these would be the requirements:
> 
> sub-packages:
> 
> * nvcc
> 
> non-cuda-sub-packages:
> 
> * libcublas
> * libcufft
> * libcusolver

I am doing this but with nvcc and toolkit in the sub-packages. Do you think toolkit might not be needed?

**Comment by oierlauzi** [comment]
Toolkit installs all libcu* packages. We could replace the toolkit by the subset of packages we are interested in.

**Comment by oierlauzi** [comment]
Currently none of them is needed, but in the future, those are the expected ones.

**Comment by MartinSalinas98** [comment]
I would merge the PR as is and then update the other branch with it and uncomment the compilation steps

**Review by MartinSalinas98 — APPROVED** [review]

**Pull request merged**
